### ISSUE TITLE
Add the possibility to send raw messages

### ISSUE THREAD

**Issue by JJ** [ijneb/telegram-bot#8]
If they have been uri-encoded on the other end, for instance. Or URI encoded only in part.
I can do a PR for this is needed; would you please add "hacktoberfest" to the topics of the repo so that it counts :-)?

**Comment by JJ** [comment]
I'm checking this, and I think we do need to send raw messages anyway. Since "get" requests go through Cro::HTTP::Get, they undergo Cro::URI transformation anyway. That would avoid error such as this one: https://github.com/croservices/cro-http/issues/115

**Comment by benjif** [comment]
I'm late to respond (sorry about not adding "hacktoberfest" in time!), but I've merged your PR. Thanks!

**Comment by JJ** [comment]
No problem :-) thanks anyway. Will you do a new release now?
